version: "3.8"
# 管理的服务
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    privileged: true
    ports:
      - 3309:3306
    volumes:
      - "./mysql/my.cnf:/etc/mysql/"
      - "./mysql/logs:/var/log/mysql"
      - "./mysql/data:/var/lib/mysql:rw"
      - "/etc/localtime:/etc/localtime"


    environment:
      # 环境变量
      - MYSQL_DATABASE=zabbix           #创建数据库
      - MYSQL_USER=zabbix               #定义用户
      - MYSQL_PASSWORD=123456           #用户密码
      - MYSQL_ROOT_PASSWORD=123456      #定义mysql root密码
    command:
      --character-set-server=utf8
      --collation-server=utf8_bin
      --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --lower_case_table_names=1
    networks:
      mynetwork:
        ipv4_address: 172.20.238.5

  zabbix-server-mysql:
    # 指定镜像
    restart: unless-stopped
    image: zabbix/zabbix-server-mysql:centos-latest
    container_name: zabbix-server-mysql
    privileged: true
    ports:
      # 端口映射
      - 10051:10051
    volumes:
      # 目录映射
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix_server/alertscripts/dingding.sh:/usr/lib/zabbix/alertscripts/dingding.sh  #钉钉告警脚本
      - ./zabbix_server/logs:/var/log/zabbix/


    links:
      - mysql
    depends_on:
      - mysql
    environment:
      # 环境变量
      - DB_SERVER_HOST=172.20.238.5
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      mynetwork:
        ipv4_address: 172.20.238.6

  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web-nginx-mysql
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=172.20.238.5
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=123456
      - ZBX_SERVER_HOST=172.20.238.6
      - PHP_TZ=Asia/Shanghai
    ports:
      - 9999:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix_web/fonts/DejaVuSans.ttf:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf  #解决图形中文乱码字体
    links:
      - mysql
      - zabbix-server-mysql
    depends_on:
      - mysql
      - zabbix-server-mysql
    networks:
      mynetwork:
        ipv4_address: 172.20.238.7




networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.20.238.0/24"
